apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        upstream fastapi-upstream {
            server fastapi-service:8000;  # Still use the service name for FastAPI
        }

        server {
            listen 80;

            location / {
                proxy_pass http://fastapi-upstream;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }
